[package]
name = "clean-git-dev"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.2"
regex = "1.5"

[profile.release]
panic = "abort"
